### ISSUE TITLE
how to generate concept embedding file  for new classes from a custom dataset?

### ISSUE THREAD

**Issue by drahmad89** [microsoft/RegionCLIP#1]

**Comment by jwyang** [comment]
Hi, @drahmad89 

You can refer to our demo code here: 
https://huggingface.co/spaces/CVPR/regionclip-demo/blob/main/detectron2/modeling/meta_arch/clip_rcnn.py#L755

And you can build a text encoder here: 
https://huggingface.co/spaces/CVPR/regionclip-demo/blob/main/detectron2/modeling/meta_arch/clip_rcnn.py#L593

**Comment by drahmad89** [comment]
@jwyang 
I wanted to get only bbox on specific classes. 
in the documentation:" put it in the folder ./datasets/lvis/lvis_v1_val.json. The file is used to specify object class names."
I replaced this "lvis_v1_val.json" with custom annotation json file that only contains 6 different classes. I ran the zeroshot detection and always getting classes from LVIS dataset. (section:Visualization on custom images)

**Comment by jwyang** [comment]
@drahmad89 , currently, visualize on custom images **does not** support user-specific queries. We had built a huggingface demo as shared above which takes one category as the query. Per your request, we will build a customized demo into this repo to support user-specific queries given an image. Please stay tuned!

**Comment by drahmad89** [comment]
I tried to create my own concept embedding by encoding my custom classes using CLIP text encoder but the CLIP encoding vector dimension is 512 while the concept embedding is 640 ("lvis_1203_cls_emb_rn50x4.pth")

**Comment by jwyang** [comment]
Hi, @zhangxgu @drahmad89 , I had included the script to extract concept embeddings for customized concept pool, please have a check. Also, @zhangxgu , your code for extracting concept embeddings seems pretty correct except that you may want to use all prompt templates and do the normalization to the output text features.

**Comment by Jawing** [comment]
The script output at the end had a dim of `(class_len, 1, emb_size)`, it is also still on gpu. I suggest to add `torch.squeeze(concept_feats).cpu()` after https://github.com/microsoft/RegionCLIP/blob/0e5e958a02661e77bdd01d9812cdc56fefd72c9c/tools/extract_concept_features.py#L101

I wasn't too sure of the format of the classes to input in concepts.txt. If it is listed line by line then shouldn't         
```
for line in f:
            concept = line.strip()
```
replace https://github.com/microsoft/RegionCLIP/blob/0e5e958a02661e77bdd01d9812cdc56fefd72c9c/tools/extract_concept_features.py#L90

Just some suggestions :)

**Comment by jwyang** [comment]
Hi, @Jawing, good suggestion!
