### ISSUE TITLE
pretraining code for RegionCLIP

### ISSUE THREAD

**Issue by jihwanp** [microsoft/RegionCLIP#10]
Hi I have a question about the code for pretraining RegionCLIP.
You only provide pretrained checkpoint in this repo and it seems there is none of the code or config for pretraining RegionCLIP.
Maybe I didn't find it, or are you planning to release it later?
Thanks!

**Comment by YiwuZhong** [comment]
Yes, we're still working on the code release for pre-training config and data. Stay tuned!

PS: If you're interested in the pre-training code, it is already released ([link](https://github.com/microsoft/RegionCLIP/blob/a4d99b239983f901ca2f9bcab0867df29fa7ea68/detectron2/modeling/meta_arch/clip_rcnn.py#L351)).

**Comment by jihwanp** [comment]
Oh it's already been there. Thanks!

**Comment by YiwuZhong** [comment]
@jihwanp I just released the configs and scripts of pre-training. Please take a look at the [update](https://github.com/microsoft/RegionCLIP#updates). It's still under construction. Feel free to use them as your reference.
