### ISSUE TITLE
Question about roi heads

### ISSUE THREAD

**Issue by childult-programmer** [microsoft/RegionCLIP#104]
Thanks for interesting research!
I'm wondering about [clip_roi_heads.py, line-248 (_shared_roi_transform)](https://github.com/microsoft/RegionCLIP/blob/4b8513b56e24827e3d6468e1f2105869f35c2d0b/detectron2/modeling/roi_heads/clip_roi_heads.py#L248).

I see that the feature map has been passed through the backbone (and of course self.backbone.layer4), so I question the intention of having it pass through backbone_res5 again after pooling (x=self.pooler(features, boxes)).
As the batch size gets larger, the number of boxes (list length) increases, so the memory consumption worsens.
How is this different from simply pooling with a pooler_resolution of 7 for the feature map, and why did you intend it to be designed this way?

Thank you!

**Comment by YiwuZhong** [comment]
@childult-programmer Pooling on layer 4 and then passing the pooled features to layer 5 is a common design of a Faster RCNN detector.

**Comment by childult-programmer** [comment]
Thanks for response!
