### ISSUE TITLE
Visualization settings with MODEL.ROI_HEADS.SOFT_NMS_ENABLED

### ISSUE THREAD

**Issue by Jawing** [microsoft/RegionCLIP#13]
Why is `MODEL.ROI_HEADS.SOFT_NMS_ENABLED True` enabled in `test_transfer_learning.sh` and not in `visualize_transfer_learning.sh`. And when it is enabled in `visualize_transfer_learning.sh` the generated images sometimes output accuracies greater than 100% for detected bounding box classes. Why is that?

**Comment by YiwuZhong** [comment]
The default inference multiplies RPN scores and 2nd-stage confidence scores together as the final score for NMS process. That is why you will see >100% confidence score. 

So in this case, we should visualize the 2nd-stage confidence score instead of the ones after multiplication. I have enabled that in regular NMS setting, but haven't got a chance to enable that for soft NMS setting. You can have a try on your own.

**Comment by Jawing** [comment]
How do you go about enabling it?

**Comment by YiwuZhong** [comment]
Refer to [this line of code](https://github.com/microsoft/RegionCLIP/blob/a4d99b239983f901ca2f9bcab0867df29fa7ea68/detectron2/modeling/roi_heads/fast_rcnn.py#L207) with [this config entry](https://github.com/microsoft/RegionCLIP/blob/a4d99b239983f901ca2f9bcab0867df29fa7ea68/configs/LVISv1-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_custom_img.yaml#L10).

**Comment by Jawing** [comment]
> Refer to [this line of code](https://github.com/microsoft/RegionCLIP/blob/a4d99b239983f901ca2f9bcab0867df29fa7ea68/detectron2/modeling/roi_heads/fast_rcnn.py#L207) with [this config entry](https://github.com/microsoft/RegionCLIP/blob/a4d99b239983f901ca2f9bcab0867df29fa7ea68/configs/LVISv1-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_custom_img.yaml#L10).

Do you mean by setting `MODEL.CLIP.MULTIPLY_RPN_SCORE False` Otherwise even with `MODEL.CLIP.VIS True` it still outputs >100% confidence score.

**Comment by YiwuZhong** [comment]
In regular NMS setting, setting `MODEL.CLIP.VIS True` can ensure visualized scores to be always <100%.

In soft NMS setting, setting `MODEL.CLIP.VIS True` cannot make the visualized scores to be <100% (not implemented yet). But you can set `MODEL.CLIP.MULTIPLY_RPN_SCORE False` to visualize scores <100%. Empirically, multiplying RPN scores during NMS process can improve the detection results.
