### ISSUE TITLE
concepts.txt files for the RegionCLIP

### ISSUE THREAD

**Issue by Hyungsik-Jung** [microsoft/RegionCLIP#16]
Hi, thank you for the nice and inspiring work!
You provide pre-training code for the RegionCLIP but I cannot find `concepts.txt` files.
Is there any plan for the providing `concepts.txt` files filtered from COCO cap. or CC3M used in your work?
Thanks :)

**Comment by YiwuZhong** [comment]
@Hyungsik-Jung Thanks for your interests. The concept files were already uploaded in the Google Drive. Please refer to the [Model Zoo downloading section](https://github.com/microsoft/RegionCLIP/blob/main/docs/MODEL_ZOO.md#model-downloading). The concept txt files and their embedding file (pth) locate at `concept_emb` subfolder.
