### ISSUE TITLE
Region classification on LVIS after fine-tuning on CC

### ISSUE THREAD

**Issue by Jeff-LiangF** [microsoft/RegionCLIP#17]
Hi, Thanks for your inspiring work! I am trying to reproduce the region classification results of your paper. Figure 1 (b) shows that the vanilla CLIP-R50 only achieves 19.1 accuracies on LVIS GT regions. I wonder what's the accuracy of your fine-tuned RegionCLIP-R50 on LVIS regions. Could you share some raw results of this part? Thanks!

**Comment by YiwuZhong** [comment]
Hi @Jeff-LiangF, I didn't test that top-1 region classification accuracy for fine-tuned detector. The top-1 accuracy was to demonstrate the gap between image-level classification and region-level classification. As a formal way to evaluate the region-level recognition ability, zero-shot object detection (Table 4) using detection metrics is a good reference.

**Comment by Jeff-LiangF** [comment]
Thanks for the clarification!
