### ISSUE TITLE
num_gpus setting for transfer learning

### ISSUE THREAD

**Issue by twangnh** [microsoft/RegionCLIP#18]
Hi yiwu, thanks for your great work and implementation, i have a question for transfer learning, in the train_transfer_learning.sh file, the num_gpus are set to 1, so does that mean you used one gpu for training, but it seems in the config the batch size is 16, which is a typical 8 gpu setting

**Comment by YiwuZhong** [comment]
@twangnh Yes, I used 8 GPUs for my experiments. I set it as 1 in the scripts for some the users who don't have 8 GPUs.

**Comment by twangnh** [comment]
noted, thanks, have you tried fewer training steps, as 90000 was used to train a normal 1x schedule model while here the RPN and CLIP are already pre-trained

**Comment by YiwuZhong** [comment]
@twangnh I followed the 1x schedule training, since the regular detectors are also pre-trained such as ImageNet backbone.

**Comment by twangnh** [comment]
got it!
