### ISSUE TITLE
support instance segmentation

### ISSUE THREAD

**Issue by linlililin123456** [microsoft/RegionCLIP#19]
I'm wondering if the project support the evaluation of open vocabulary instance segmentation? Thanks!

**Comment by YiwuZhong** [comment]
Yes, all scripts for detectors fine-tuned on LVIS support open-vocabulary instance segmentation, including training and evaluateion (set `MASK_ON` as `True`).

**Comment by linlililin123456** [comment]
thanks for the reply, so COCO is currently not supported? could you suggest how to modify it?

**Comment by YiwuZhong** [comment]
@linlililin123456 The codebase has also supported instance segmentation on COCO. Exactly the same as Detectron2, simply  setting `MASK_ON` as `True` should enable the segmentation (Mask RCNN).

**Comment by linlililin123456** [comment]
thanks!
