### ISSUE TITLE
how to run baseline clip detection model

### ISSUE THREAD

**Issue by twangnh** [microsoft/RegionCLIP#2]
Hi! Thanks for your impressive work! I'm wondering is it possible to run the baseline CLIP detection in table 4 with the released code?

**Comment by jwyang** [comment]
Hi, @twangnh, thanks for your suggestion! We will add that evaluation into this repo. Will let you know once completed.

**Comment by YiwuZhong** [comment]
Hi @twangnh, the released code has already supported the evaluation on CLIP (Table 4 results). 

You can find the CLIP weights in our [Model Zoo](https://github.com/microsoft/RegionCLIP/blob/main/docs/MODEL_ZOO.md#clip-models). After downloading it, simply replace our RegionCLIP weights (e.g., in [this script](https://github.com/microsoft/RegionCLIP/blob/e4838f6cf0988f816b0465704ae42b0d4a2e2f7b/test_zeroshot_inference.sh#L8)) to CLIP weights (e.g., `./pretrained_ckpt/clip/teacher_RN50_student_RN50_OAI_CLIP.pth`). Then the results at Table 4 can be reproduced.

**Comment by twangnh** [comment]
@jwyang @YiwuZhong Thanks for noting to me, just to make sure, I'm wondering if the CLIP weights (./pretrained_ckpt/clip/teacher_RN50_student_RN50_OAI_CLIP.pth) are the same as original CLIP?

**Comment by YiwuZhong** [comment]
@twangnh Yes, the weights are the same as original CLIP. We copied CLIP's weights into this file to make Detectron2 convenient to load the pre-trained weights.

**Comment by twangnh** [comment]
thanks!
