### ISSUE TITLE
MODEL.CLIP.NO_BOX_DELTA

### ISSUE THREAD

**Issue by Jawing** [microsoft/RegionCLIP#20]
Could I get an explanation for this setting and how it is used and its effect on inference? How come it's turned on for visualization and not for test/train/inference settings?

**Comment by YiwuZhong** [comment]
@Jawing As explained in [default.py](https://github.com/microsoft/RegionCLIP/blob/aca5ce505f18912823427f13c2421ad58fbc4894/detectron2/config/defaults.py#L203), this flag was used to disable the 2nd-stage box regression. Usually the detector learns from human annotation to predict the box delta and apply it to the region proposals. But during pre-training and zero-shot inference, there is no human-annotated boxes used to learn the box regression and thus we directly use the region proposals (e.g., RPN).

**Comment by Jawing** [comment]
If I understand correctly, box deltas are transformations learned from human-annotated boxes (base dataset) and then applied to region proposals. Therefore it should improve inference performance on base datasets (trained on) compared to novel datasets when turned on.

**Comment by YiwuZhong** [comment]
@Jawing Yes, the deltas are learned from human boxes. Empirically, the box trained on base categories can also generalize to novel categories with acceptable performance drop. Good generalization of object location (e.g., region proposals, box delta learning) is a direction to explore.
