### ISSUE TITLE
query about the mask annotation in LVIS training

### ISSUE THREAD

**Issue by motoight** [microsoft/RegionCLIP#21]
Hi, RegionClip is a great work and I am interested in how it works.
I notice that you have used mask annotation in training detector. But I didn't find the reason why you use it. Did it helps improving the generalization of the detector? I didn't find any ablation study about this mask annotation. 
I am look forward that you can give me some help! 
Thanks !

**Comment by YiwuZhong** [comment]
@motoight Thanks for your interests! As described at Setup in section 4.1.1 of paper, mask annotation is used to compare with ViLD on LVIS benchmark.

**Comment by motoight** [comment]
Thanks!
