### ISSUE TITLE
Zero-shot Inference with custom categories

### ISSUE THREAD

**Issue by williamberrios** [microsoft/RegionCLIP#22]
Hi, I wanted to ask if it's possible to use the code from the section "Visualization on custom images" to extract bbox and categories using a custom vocabulary. Should I just create my custom concept embeddings (./pretrained_ckpt/concept_emb)?

**Comment by YiwuZhong** [comment]
@williamberrios Yes, you can leverage the existing code for zero-shot inference with custom categories. This can be done by replacing our concept embedding with the ones you created. After inference, you might have to modify the visualization code a bit for your custom categories (e.g., the class names).
