### ISSUE TITLE
 'Non-existent config key: MODEL.CLIP'

### ISSUE THREAD

**Issue by sekar1112** [microsoft/RegionCLIP#23]
while running visualize_zeroshot_inference.sh i grt the error as  'Non-existent config key: MODEL.CLIP' so can anyone help me with this ??

**Comment by YiwuZhong** [comment]
@sekar1112 We have not met this error before. One possibility is that your installation is not correct. For example, you installed original Detectron2 but not our RegionCLIP. In this case, the code only has the config keys from Detectron2 and cannot find our keys (MODEL.CLIP). You can strictly follow our installation and try again.

**Comment by cjf-repo** [comment]
> while running visualize_zeroshot_inference.sh i grt the error as 'Non-existent config key: MODEL.CLIP' so can anyone help me with this ??

@sekar1112 
I meet the same problem, how do you solve it?

**Comment by lanternjx** [comment]
I meet the same problem, case I strictly followed your installation, but it comes that your version is wrong, so I installed original Detectron2. But original Detectron2 'Non-existent config key: MODEL.CLIP'. so what should i do to install your detectron
