### ISSUE TITLE
Question about the teacher model in pre-train stage.

### ISSUE THREAD

**Issue by cuiziteng** [microsoft/RegionCLIP#24]
Dear Author, thanks for your excellent research and code! I still have some questions in the pre-training stage.

The teacher model you mention in the pre-train stage, the backbone is the CLIP visual encoder, and the RPN is the pre-train RPN on base class, so could it get a reliable score with backbone (CLIP weights) + RPN (Other weights)? 

I'm wondering about this because I found that the final layer in CLIP visual encoder is an attention pooling layer, from my experiments I found that the attention pooling would damage the performance location ability in the ResNet model. How do you avoid this problem, thanks! 🙏

**Comment by YiwuZhong** [comment]
Hi @cuiziteng, thanks for your interests iin our work. 

I don't fully understand your questions. Did you mean the performance of combining CLIP + RPN together? If so, all CLIP baselines in Table1-4 of paper evaluates its performance in different settings. For attention pooling, I cannot answer your question without the context. I think the attention pooling is required to fully make use of CLIP's knowledge.
