### ISSUE TITLE
pretraining process

### ISSUE THREAD

**Issue by mactavish91** [microsoft/RegionCLIP#26]
Hello, your research is great! I am very interested in the code of the pretraining process. Is this part of the code open source?

**Comment by YiwuZhong** [comment]
@mactavish91 Thanks for your interests in our work. Yes, the pre-training code was already released (see [PretrainFastRCNN](https://github.com/microsoft/RegionCLIP/blob/aca5ce505f18912823427f13c2421ad58fbc4894/detectron2/modeling/meta_arch/clip_rcnn.py#L351)). The only part left is the data files (images and captions). We're now still working the data files.
