### ISSUE TITLE
Image Augmentation with bounding boxes

### ISSUE THREAD

**Issue by Jawing** [microsoft/RegionCLIP#28]
I'd like to understand how to add image augmentation with bounding box coordinates such as [copy_paste](https://github.com/conradry/copy-paste-aug) and [albumentations bbox augmentations](https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/) to the training/finetuning setup.

It seems that you can set transformations in [detectron2/data/dataset_mapper.py](https://github.com/microsoft/RegionCLIP/blob/aca5ce505f18912823427f13c2421ad58fbc4894/detectron2/data/dataset_mapper.py#L99)
and from functions in utils folder like `utils.transform_instance_annotations`, `utils.build_augmentation(cfg, is_train)`
How does the current INPUT.RANDOM_FLIP transformation transform bounding boxes of the original image?
I'm not sure how to properly add the recomputed_boxes for the copy_paste method.

Any tips?

**Comment by YiwuZhong** [comment]
@Jawing RegionCLIP uses the default data augmentation in Detectron2 (e.g., scale image to (800,1333) size, flipping), but didn't use copy-paste. Detectron2 supports large-scale jittering while requires much longer training time. Beyond that, I didn't figure out a direct way to inject those implementation of copy-paste techniques into Detectron2 framework.
