### ISSUE TITLE
Colab Notebook

### ISSUE THREAD

**Issue by Siegi96** [microsoft/RegionCLIP#32]
Hey, thanks for the impressive work. Would it be possible to add a Colab Tutorial Notebook using the pretrained models?

**Comment by YiwuZhong** [comment]
@Siegi96 We've provided step-by-step tutorial in README (eg, [zero-shot inference](https://github.com/microsoft/RegionCLIP#visualization-on-custom-images)). Colab tutorial would be simply copy-paste the script from tutorial above.
