### ISSUE TITLE
Is there a way to finetune RPN during transfer learning?

### ISSUE THREAD

**Issue by drahmad89** [microsoft/RegionCLIP#33]

**Comment by YiwuZhong** [comment]
Yes, the offline RPN we use is the exact module in Detectron2. So you simply [enable gradient updating](https://github.com/microsoft/RegionCLIP/blob/9fd374015db384bc0548b4af85446b90e13d2ae1/detectron2/modeling/meta_arch/clip_rcnn.py#L130) for this RPN and then attach the regular RPN loss to train it.
