### ISSUE TITLE
What is RN50*4?

### ISSUE THREAD

**Issue by YifanXu74** [microsoft/RegionCLIP#34]
Hi, nice work！
I am confused about the backbone RN50*4 used in the paper. Is it a RN50 network with 4 stages FPN? And what is the difference with the RN50-FPN in ViLD?
Thank you for your kindly help.

**Comment by YiwuZhong** [comment]
@YifanXu74 Thanks for your interests. We didn't use any FPN in our backbones. It was a backbone used in [CLIP](https://github.com/openai/CLIP). It's deeper and wider ResNet (see details of blocks in each stage at [this link](https://github.com/microsoft/RegionCLIP/blob/9fd374015db384bc0548b4af85446b90e13d2ae1/detectron2/modeling/backbone/clip_backbone.py#L693)).

**Comment by YifanXu74** [comment]
I got it! Thanks a lot!
