### ISSUE TITLE
Add a linear probe

### ISSUE THREAD

**Issue by drahmad89** [microsoft/RegionCLIP#35]
For some experimental reasons, I want to test the performance with a Linear Probe and step away from the text embeddings. The code is very abstract and I would like to get some help or point me to where I should change the code to make classification head work in a traditional way. I have a custom dataset and would like to do fine-tuning but. In other words, make it work as a traditional object detector

**Comment by YiwuZhong** [comment]
@drahmad89 [This line](https://github.com/microsoft/RegionCLIP/blob/9fd374015db384bc0548b4af85446b90e13d2ae1/detectron2/modeling/roi_heads/fast_rcnn.py#L442) is the starting point for text-embedding-based classifier.
