### ISSUE TITLE
Question about train_transfer_learning

### ISSUE THREAD

**Issue by Martin0401** [microsoft/RegionCLIP#37]
Hi yiwu:
I have a question. When runing train_transfer_learning.sh,  I find there are no RPN losses, whether RPN is frozen?

**Comment by YiwuZhong** [comment]
@Martin0401 Yes, you're right. RPN was pre-trained by base categories and wasn't updated during transfer learning (refer to [Line 209](https://github.com/microsoft/RegionCLIP/blob/9fd374015db384bc0548b4af85446b90e13d2ae1/detectron2/modeling/meta_arch/clip_rcnn.py#L209)).

**Comment by Martin0401** [comment]
Thank you for your reply, Whether can I update RPN during transfer learning, and how to do it? Thank you

**Comment by YiwuZhong** [comment]
@Martin0401 Simply setting RPN to training mode should work. For example, comment out the block in [Line 129](https://github.com/microsoft/RegionCLIP/blob/9fd374015db384bc0548b4af85446b90e13d2ae1/detectron2/modeling/meta_arch/clip_rcnn.py#L129) and [Line 210](https://github.com/microsoft/RegionCLIP/blob/9fd374015db384bc0548b4af85446b90e13d2ae1/detectron2/modeling/meta_arch/clip_rcnn.py#L210).
