### ISSUE TITLE
Memory leak during ovod finetuning

### ISSUE THREAD

**Issue by motoight** [microsoft/RegionCLIP#38]
Nice works ! 
I am working on ovod problem right now.
I am using your code to reproduce your ovod finetuning results on region-clip pretrain weights. In order to get quick response on testing, I modified the TEST.EVAL_PERIOD=5000( the original one is 25000), but I found the whole training process will be interrupted by an unexpected error around iter 60k, which is about 12 evaluation during the time .

> Traceback (most recent call last):
>   File "/home/wulei04/miniconda3/envs/detic/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
>     obj = _ForkingPickler.dumps(obj)
>   File "/home/wulei04/miniconda3/envs/detic/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
>     cls(buf, protocol).dump(obj)
>   File "/home/wulei04/miniconda3/envs/detic/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 312, in reduce_storage
>     metadata = storage._share_filename_()
> RuntimeError: error executing torch_shm_manager at "/home/wulei04/miniconda3/envs/detic/lib/python3.8/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99
> Traceback (most recent call last):
>   File "/home/wulei04/miniconda3/envs/detic/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
>     obj = _ForkingPickler.dumps(obj)
>   File "/home/wulei04/miniconda3/envs/detic/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
>     cls(buf, protocol).dump(obj)
>   File "/home/wulei04/miniconda3/envs/detic/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 312, in reduce_storage
>     metadata = storage._share_filename_()
> RuntimeError: error executing torch_shm_manager at "/home/wulei04/miniconda3/envs/detic/lib/python3.8/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99
> 

I suspected that it was caused by the cpu memory leak, so l log the cpu free memory each 5secs and plot it, it shows that the cpu memory continuely decrease. 
I make a little difference during the training process, but no modification in dataloading and evaluation. I am wondering how to fix it, and which part may be the root cause of this memory leak issue?
![image](https://user-images.githubusercontent.com/39431667/199666099-bffb35ac-3190-42b6-b6b0-91901075a268.png)

**Comment by YiwuZhong** [comment]
@motoight Thanks for visualize this issue. We used Detectron2 to train the model, without changing the underlying code structure. Did you observe the same trend using original Detectron2 library?

**Comment by motoight** [comment]
> @motoight Thanks for visualize this issue. We used Detectron2 to train the model, without changing the underlying code structure. Did you observe the same trend using original Detectron2 library?

No. I just verify this problem in your codebase.

**Comment by YiwuZhong** [comment]
@motoight I would suggest running the Detectron2 model (RegionCLIP repo still supports original Detectron2 commands) and check the memory. If the issues keeps the same, you could try commenting out `torch.multiprocessing.set_sharing_strategy('file_system')` in the train file.
