### ISSUE TITLE
Configs for the Hugging Face demo please.

### ISSUE THREAD

**Issue by Fitzwong** [microsoft/RegionCLIP#39]
Great work!
I've been trying to reproduce the Hugging Face demo of RegionCLIP (given a text description, and return a bounding-box).
I tried the default config (given in extract_region_features.sh) and other combinations of pre-trained models, but still cannot reach the accuracy of the demo.
When I run the app.py downloaded from Hugging Face, I found that text and image cannot be put into the model together.
So may I ask which config you use in the hugging face demo?

**Comment by YiwuZhong** [comment]
@Fitzwong We used the same zero-shot config file in this codebase. Hugging Face demo is a bit different in terms of the number of predicted boxes (eg, only one box is visualized).
