### ISSUE TITLE
prepare  pretrain datasets

### ISSUE THREAD

**Issue by lattens** [microsoft/RegionCLIP#45]
Great work!
I've been trying to reproduce this work.
If I want to pretrain a model on the Coco Caption dataset, how do I prepare the Coco Caption datasets format? What's image_tsv_file and text_tsv_file? How do I convert Coco Caption datasets into them?

**Comment by YiwuZhong** [comment]
Hi @lattens, the inputs are simply image pixels and sentence strings. I'd suggest you write the data loading part for your own usage. The tsv files we used are special internal format.
