### ISSUE TITLE
New datasets

### ISSUE THREAD

**Issue by sinamalakouti** [microsoft/RegionCLIP#46]
Hi, 
Great paper and repository!
I was wondering how I can use the pre-trained model to fine-tune and evaluate on other datasets such as Pascal Voc?

**Comment by YiwuZhong** [comment]
Our code is built on Detectron2 which already supports [Pascal Voc](https://github.com/microsoft/RegionCLIP/tree/main/configs/PascalVOC-Detection). The major components you need to prepare to include the config file for the new dataset and concept embeddings for target categories (refer to [our tutorial](https://github.com/microsoft/RegionCLIP#extract-concept-features)).
