### ISSUE TITLE
transfer_learning with custom datasets

### ISSUE THREAD

**Issue by better629** [microsoft/RegionCLIP#47]
Refs to the `Transfer Learning` in the `README.md`,  If I trained with the custom datasets(for example, with 5 classes)
There would be a shape mismatch in `detectron2/modeling/roi_heads/fast_rcnn.py`
```
                if clip_cls_emb[1] is not None: # it could be None during region feature extraction
                    pre_computed_w = torch.load(clip_cls_emb[1])  # [num_classes, 1024] for RN50
                    self.cls_score.weight.copy_(pre_computed_w)
```

So, How do I generate a custom `MODEL.CLIP.TEXT_EMB_PATH` file with the pretrained models.

**Comment by YiwuZhong** [comment]
Please refer to our guidance for generating the custom concept embeddings: https://github.com/microsoft/RegionCLIP#extract-concept-features
