### ISSUE TITLE
How to generate the concepts for Cap/CC3M?

### ISSUE THREAD

**Issue by xingkongliang** [microsoft/RegionCLIP#48]
Thanks for the great work！
In the paper, "Object concepts whose frequency are lower than 100 are discarded, leading to 4764/6790 concepts on COCO Cap/CC3M." The number of concepts I generated is quite different from the number of papers. Can you provide the generation script?

**Comment by wusize** [comment]
The same question. Cound the author provide the code for generating the concepts or the text file of them. I have a script but only generate 1152 concepts.

**Comment by wusize** [comment]
```import sng_parser
import json
from tqdm import tqdm

caption_file = 'data/coco/annotations/captions_train2017_tags_allcaps.json'

with open(caption_file, 'r') as f:
    caption_json = json.load(f)


image_infos = caption_json['images']

concepts2cnt = {}

for img_info in tqdm(image_infos):
    cpts = []
    captions = img_info['captions']
    for cap in captions:
        graph = sng_parser.parse(cap)
        entities = graph['entities']
        cpts += [ent['head'] for ent in entities]

    cpts = list(set(cpts))
    for cpt in cpts:
        if cpt in concepts2cnt:
            concepts2cnt[cpt] += 1
        else:
            concepts2cnt[cpt] = 1

pronouns = ['I', 'i', 'you', 'You', 'we', 'We', 'They', 'they',
            'it', 'It', 'He', 'he', 'She', 'He', 'This', 'this',
            'That', 'that', 'Yours', 'yours', 'her', 'Her',
            'His', 'his', 'Their', 'their', 'ours', 'Ours', 'what', 'What', 'Who', 'who',
            'Which', 'which', 'Whose', 'whose', 'whatever', '-', 'A', 'a']

concepts = [k for k, v in concepts2cnt.items() if v >= 100 and k not in pronouns]

print(f'Get {len(pronouns)} concepts')
with open('data/coco/coco_train_concepts.json', 'w') as f:
    json.dump({cpt: concepts2cnt[cpt] for cpt in concepts}, f)

**Comment by YiwuZhong** [comment]
To parse the nouns from sentences, we use [this parser](https://github.com/vacancy/SceneGraphParser) which is based on Spacy library and manually-designed parsing rules. After parsing the triplets from all sentences, keep the unique nouns with most frequency.

**Comment by YiwuZhong** [comment]
> The same question. Cound the author provide the code for generating the concepts or the text file of them. I have a script but only generate 1152 concepts.

Thanks for sharing the script. I found that the frequency was set to 10 for COCO captions, yet 100 for CC3M captions as reported in the paper. Since CC3M has much more sentences than COCO, the threshold was set accordingly. However, our method is less sensitive to this threshold and should perform closely using 1152 vs. 4764 nouns.
