### ISSUE TITLE
I take the liberty to disturb you. I found that the result of the picture annotation is incorrect during the test

### ISSUE THREAD

**Issue by zmw1003** [microsoft/RegionCLIP#52]
I strictly follow these two steps without any change
![99b8e01c01095b4c0417418b12688a7](https://user-images.githubusercontent.com/91039392/220539832-730af871-b3d9-454b-9e6a-e6c61755b0e7.png)
But the result of my output picture is like this, which makes me very distressed. I hope I can get help
![3f74b1699e4fdc8fe298d40f36bd6a1](https://user-images.githubusercontent.com/91039392/220539961-450ae189-550c-4757-a469-63fc83643582.png)
![7fb486f8f6842fce20d4f0bdebe0b45](https://user-images.githubusercontent.com/91039392/220539967-c465fe79-b84e-4267-a127-ded680128208.png)

**Comment by YiwuZhong** [comment]
The scripts work well on other users' machines. It's not totally sure which part is not settled down on your side. You could try debugging the results. For example, in the visualization script, print the confidence scores of predicted boxes. The highest scores above are around 21% which is quite low.
