### ISSUE TITLE
Evaluation time on transfer learning

### ISSUE THREAD

**Issue by bbln33** [microsoft/RegionCLIP#55]
Dear author,

Thanks for nice works!
I have a question of the inference time on transfer learning.
As you described in README, I run the evaluate script below:
```
python3 ./tools/train_net.py \
--eval-only  \
--num-gpus 8 \
--config-file ./configs/COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml \
MODEL.WEIGHTS ./pretrained_ckpt/regionclip/regionclip_finetuned-coco_rn50.pth \
MODEL.CLIP.OFFLINE_RPN_CONFIG ./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x_ovd_FSD.yaml \
MODEL.CLIP.BB_RPN_WEIGHTS ./pretrained_ckpt/rpn/rpn_coco_48.pth \
MODEL.CLIP.TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/coco_48_base_cls_emb.pth \
MODEL.CLIP.OPENSET_TEST_TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/coco_65_cls_emb.pth \
MODEL.ROI_HEADS.SOFT_NMS_ENABLED True \
```
I use NVIDIA 3090 8 gpus, but I guess it is little bit too long for evaluation.
Is is possible to share the inference time on transfer learning?

**Comment by Therock90421** [comment]
Hi！
Thanks for this great work！
However，I face the same thing. When I inference on a V100, it takes 10 seconds to infer 1 image. Is that normal?

**Comment by Therock90421** [comment]
OKAY I have found my mistake, bad weight loading. FYI, mine is 1s/ iter.

**Comment by xiaofeng94** [comment]
Hey @bbln33, I met the same problem. It takes me ~1 hour on COCO validation, but a standard mask-rcnn provided by detectron2 only takes minutes. Did you solve it? Could you provide us how long it takes with your environment?

**Comment by bbln33** [comment]
In my case, the whole inference time is around 4 hours. I found that it depends on the `MODEL.ROI_HEADS.SOFT_NMS_ENABLED` option. When it sets `true`, it takes more time than `false`.
