### ISSUE TITLE
Can I run this on cpu 

### ISSUE THREAD

**Issue by manthansinghshekhawat** [microsoft/RegionCLIP#56]
I am running extract_region_feature.py and it's showing torch is not compatible with cuda I don't have cuda enabled gpu can I run this code on cpu only

**Comment by YiwuZhong** [comment]
This is a good question. But unfortunately, I haven't tried that before.  Our codebase is built on top of Detectron2 and thus I'd recommend searching the usage of Detectron2. One quick solution is simply removing all `.cuda()` in the data loading and model forward, which port tensor onto GPU.
