### ISSUE TITLE
Easy Way to Use Extracted Features

### ISSUE THREAD

**Issue by kilickaya** [microsoft/RegionCLIP#57]
Hello, 

Many thanks for your impressive work and proving the code for extracting features. I am trying to replicate the findings of this work: [Open-Vocabulary Object Detection upon Frozen Vision and Language Models (ICLR'23)](https://openreview.net/forum?id=MIMwy4kh9lf)

I wonder if there is an easy way to build upon extracted features, assuming that the backbone CLIP will be frozen throughout the learning? One way I could think of is to simply write an alternative data loader to load features instead of images, but wanted to ask beforehand.

**Comment by YiwuZhong** [comment]
I agree with your idea. If you only use frozen CLIP and its fixed features, it's better to extract features, save them in disks, and load them in Dataloader. It will save you much time without running CLIP model at each iteration.
