### ISSUE TITLE
AP on ground truth region

### ISSUE THREAD

**Issue by erjui** [microsoft/RegionCLIP#59]
Hello, thank you for the nice work first of all! 
Now I am trying to retrieve the result from table 4 using ground truth boxes. But the thing is that I thought precisions should be always the same if I use ground truth boxes, but the result seems to be different over different thresholds. So could you give a little explanation about this?!

<img width="971" alt="image" src="https://user-images.githubusercontent.com/36221725/235816878-4da0518d-1cee-45eb-9102-c80e9b5e3614.png">

**Comment by YiwuZhong** [comment]
The results seem to be quite close across different thresholds (61.0 vs. 61.4 vs. 61.0). One possibility is that the difference is caused by the precision during floating-point computation.
