### ISSUE TITLE
您好，训练自己的数据集可以提供详细的教程吗？这对于我们做下游任务会非常有帮助。

### ISSUE THREAD

**Issue by binyisu** [microsoft/RegionCLIP#62]

**Comment by binyisu** [comment]
”Put all concepts in the file concepts.txt with each line as a concept name.“ 比方说我自己的数据集如何命名concept name。A photo of stone 这种吗？

**Comment by YiwuZhong** [comment]
The text you put in "concepts.txt" is simply the names of objects. Our code will generate language embeddings for these concepts, by using sentence prompts such as "a photo of xxx".

**Comment by binyisu** [comment]
> The text you put in "concepts.txt" is simply the names of objects. Our code will generate language embeddings for these concepts, by using sentence prompts such as "a photo of xxx".

您的coco数据集的concepts.txt方便提供下吗？我想结合coco的concepts，加上我自己数据集的一些独有类别（因为我的数据集和coco有重合的类别如person, cat, dog），一起训练一个模型，检测我的数据的特有类别如obstacle （当做novel类）。
~
~
~
或者如何在您原有的coco>coco_65_cls_emb.pth基础上继续扩充新的concept？

**Comment by YiwuZhong** [comment]
The categories of COCO dataset can be either found in their official website, or [this file](https://github.com/microsoft/RegionCLIP/blob/main/detectron2/data/datasets/builtin_meta.py).
