### ISSUE TITLE
Very poor result when evaluate on Pascal VOC dataset 

### ISSUE THREAD

**Issue by kent252** [microsoft/RegionCLIP#64]
Thanks for your's excellent paper and repository!
But I have a problem when I try to evaluate on some datasets. I follow instructions in this #46 
I try to evaluate the pre-trained RegionClip on Pascal VOC by using this command 
- To create content embedding
`!python3 ./tools/extract_concept_features.py \
--config-file ./configs/LVISv1-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_zsinf.yaml \
MODEL.WEIGHTS ./pretrained_ckpt/regionclip/regionclip_pretrained-cc_rn50.pth \
MODEL.CLIP.OFFLINE_RPN_CONFIG ./configs/LVISv1-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml \
INPUT_DIR ./datasets/custom_concepts \
OUTPUT_DIR ./output/concept_feats \
MODEL.CLIP.GET_CONCEPT_EMB True `
- Using this to evaluate 
`!python3 ./tools/train_net.py \
--eval-only  \
--num-gpus 1 \
--config-file ./configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml \
MODEL.WEIGHTS ./pretrained_ckpt/regionclip/regionclip_pretrained-cc_rn50.pth \
MODEL.CLIP.TEXT_EMB_PATH ./output/concept_feats/concept_embeds.pth \
MODEL.CLIP.CROP_REGION_TYPE GT \
MODEL.CLIP.MULTIPLY_RPN_SCORE False `

BUT I get very poor results. Can you help me with this
<img width="747" alt="Screenshot 2023-05-22 at 10 04 25" src="https://github.com/microsoft/RegionCLIP/assets/69420723/9969db92-0272-4407-a318-cfb5e3d528e0">

**Comment by helloiammoon** [comment]
@kent252
