### ISSUE TITLE
The result of RPN is close to 0 for zero-shot inference of own dataset, however, the result of GT is very good. What should I do?

### ISSUE THREAD

**Issue by QHCV** [microsoft/RegionCLIP#67]
Dear Author,
Very great work. I am getting close to 0 results for inference at RPN at zero-shot inference and very good results for inference at GT. What should I do in this case and the results are poor when doing Transfer Learning, I suspect that it is also due to RPN. What should I do?
think you.

**Comment by mlzxy** [comment]
What I do is to merge the weights of RPN and pretrained models and don't provide RPN checkpoint, i.e., only provide one model checkpoint with `MODEL.WEIGHTS`.  Then the mAP in paper can be reproduced.

**Comment by YiwuZhong** [comment]
Thanks for your interest in our work. According to your descriptions, the low performance is caused by localization errors. You could try training an RPN on your own dataset. This should provide a reasonable performance between 0 and GT boxes.

**Comment by whhong5** [comment]
> g

I have also encountered the same situation. Would you be willing to further explain this phenomenon? I also believe that the decrease in accuracy is due to a localization issue, but I do not understand why the AP value would be close to 0.

**Comment by whhong5** [comment]
> Thanks for your interest in our work. According to your descriptions, the low performance is caused by localization errors. You could try training an RPN on your own dataset. This should provide a reasonable performance between 0 and GT boxes.

Hello! I have tried to train an RPN on my own dataset. However, even if the RPN model shows that it could predict the catogories on the AP around 60, when I try to use the RPN model weight in RegionCLIP (I just simplily replace the model weight, I guess it may have some mistakes but I didn't find), the AP is not closed to 0 but relatively low (around 5 on some categories and also be closed to 0 on the others). And the GT boxes performs quite good.  Could you please give me some advice concerning using my own RPN model?

**Comment by YiwuZhong** [comment]
@whhong5 According to your descriptions, the RPN you loaded from RegionCLIP seems a bit off. If your own RPN is using exactly the same module as RegionCLIP's RPN, please check the weight loading. If not, you might need to additionally check the module definition & preprocess & feedforward functions.

**Comment by whhong5** [comment]
> @whhong5 According to your descriptions, the RPN you loaded from RegionCLIP seems a bit off. If your own RPN is using exactly the same module as RegionCLIP's RPN, please check the weight loading. If not, you might need to additionally check the module definition & preprocess & feedforward functions.

I have check the weight loading and I am not sure whether it is right or wrong.
I would like to describe my processing in detail. I would appreciate it if you would like to give me some sugguestions.(By the way, I use Google Colab to finish my project. )

Actually, I try to train the RPN by using the train_transfer_learning.sh, like this one:
`### train RPN PPE12
!python3 ./tools/train_net.py \
--num-gpus 1 \
--config-file ./configs/COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml \
MODEL.WEIGHTS ./pretrained_ckpt/regionclip/regionclip_pretrained-cc_rn50x4.pth \
MODEL.CLIP.OFFLINE_RPN_CONFIG ./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x_ovd_FSD.yaml \
MODEL.CLIP.TEXT_EMB_PATH /content/drive/MyDrive/RegionCLIP/output/concept_feats/PPE12_rn50x4.pth \
MODEL.CLIP.OPENSET_TEST_TEXT_EMB_PATH /content/drive/MyDrive/RegionCLIP/output/concept_feats/PPE12_rn50x4.pth \
MODEL.CLIP.TEXT_EMB_DIM 640 \
MODEL.RESNETS.DEPTH 200 \
MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION 18 ` 

I removed the MODEL.CLIP.BB_RPN_WEIGHTS this time, I think when I run this code, it would get a new RPN model which is initialized by "detectron2://ImageNetPretrained/MSRA/R-50.pkl" (actually I have the RPN model weight which was trained by detection2 before—— according to COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml)

However, When I run this code, it works well in the training phase and I got the model_final.pth. But it would remind me that ——
*********** 
"RuntimeError: CUDA error: invalid configuration argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions."
*************

Then I tried to use the test_transfer_learning.sh part, which is like this one:
`# RN50x4, RPN, PPE12
!python3 ./tools/train_net.py \
--eval-only  \
--num-gpus 1 \
--config-file ./configs/COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml \
MODEL.WEIGHTS /content/drive/MyDrive/RegionCLIP/output/model_final.pth \
MODEL.CLIP.TEXT_EMB_PATH /content/drive/MyDrive/RegionCLIP/output/concept_feats/PPE12_rn50x4.pth \
MODEL.CLIP.CROP_REGION_TYPE RPN \
MODEL.CLIP.MULTIPLY_RPN_SCORE True \
MODEL.CLIP.OFFLINE_RPN_CONFIG /content/drive/MyDrive/RegionCLIP/output/config.yaml \
MODEL.CLIP.BB_RPN_WEIGHTS /content/drive/MyDrive/RegionCLIP/output/model_final.pth \
MODEL.CLIP.TEXT_EMB_DIM 640 \
MODEL.ROI_HEADS.SCORE_THRESH_TEST 0.2 \
MODEL.RESNETS.DEPTH 200 \
MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION 18`

Then I got the wrong result. (Which I  mentioned before —— the inference result is close to 0). 
Actually, I am not sure the config file was used correctly or not. Would you mind giving some guidance?
（If I use the RPN model which I trained according COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml, I think I should change MODEL.CLIP.OFFLINE_RPN_CONFIG corresponding to it ?）
