### ISSUE TITLE
How to train the RPN?

### ISSUE THREAD

**Issue by mlzxy** [microsoft/RegionCLIP#68]
Hi, 

I try to retrain the `coco_48_rpn` model with [rpn_R_50_C4_1x.yaml](https://github.com/microsoft/RegionCLIP/blob/main/configs/COCO-Detection/rpn_R_50_C4_1x.yaml) and datasets `coco_2017_ovd_b_train`. But I only get AR `40.1` on `coco_2017_ovd_all_test`, while your pretrained checkpoint has an AR around `44.2`. 

Would you share some training details about the RPN network? I really appreciate your help!

**Comment by YiwuZhong** [comment]
I don't quite remember the training details of the RPN network. Have you ever tried training RPN for a longer time, such as a 3x schedule?
