### ISSUE TITLE
About custom data set RPN training.

### ISSUE THREAD

**Issue by minnie-lin** [microsoft/RegionCLIP#70]
You did a great job! I am currently working on an open vocabulary project, and I hope to apply my own data set to it. Details about your work on transfer learning on open vocabulary, where is the section on RPN training on custom datasets? I can't find it, and hope you can explain the RPN specific training commands.

**Comment by YiwuZhong** [comment]
Hi @Betricy, our codebase is built on top of Detectron2 and follows the same mechanisms as Detectron2. To train a RPN on custom dataset, Detectron2 documents would be a good starting point, such as how to define your own dataset and which RPN config to use.

**Comment by Betricy** [comment]
好的，谢谢你的回答。上面的问题已经解决了，但是最近我在训练迁移学习部分时，一开始跑loss正常减小，但是学习率一直变大，然后基本上在第四五百个iteration的时候，loss会突然变成nan，如下：loss_dict = {'loss_cls': nan, 'loss_box_reg': nan}。这个是上面的问题呢？你们训练过程中同样用的这个参数有出现相同爆炸的问题吗？

**Comment by minnie-lin** [comment]
> 你好@Betricy，我们的代码库构建在 Detectron2 之上，并遵循与 Detectron2 相同的机制。要在自定义数据集上训练 RPN，Detectron2 文档将是一个很好的起点，例如如何定义自己的数据集以及要使用的 RPN 配置。

好的，谢谢你的回答。上面的问题已经解决了，但是最近我在训练迁移学习部分的时候，一开始跑loss正常减少，但是学习率一直变大，然后基本上在第四五十个迭代的时候，loss会突然变成nan，如下：loss_dict = {'loss_cls': nan, 'loss_box_reg': nan}。这是上面的问题呢？你们训练过程中同样用的这个参数出现了相同爆炸的问题吗？

**Comment by YiwuZhong** [comment]
@Betricy You could try different values for background class weight and the gamma (see Implementation in paper).
