### ISSUE TITLE
Transfer learning training novel classes results are very low

### ISSUE THREAD

**Issue by minnie-lin** [microsoft/RegionCLIP#77]
When performing transfer learning on a custom dataset, concept embedding, RPN training, and training are all carried out according to the specified command line, but the final verification result is that the mAP of the novel classes is particularly low, and the base classes is very high.

**Comment by SamXiaosheng** [comment]
Hello，chould you show that the result the mAP of the novel classes and base classes?

**Comment by minnie-lin** [comment]
> Hello，chould you show that the result the mAP of the novel classes and base classes?
about
novel：0.18 ，base：33

**Comment by Betricy** [comment]
> 你好，你能显示一下小说类和基类的mAP结果吗？
about novel：0.18 ，base：33

**Comment by SamXiaosheng** [comment]
i found that the result of AP is very low about 37.8 when training transfer-learning for coco datasets with fully supervised object detection for all of classes.

**Comment by YiwuZhong** [comment]
Hi @Betricy @SamXiaosheng, thanks for your interest in our work. It's not totally sure which part goes wrong when you adapt the pipeline to your custom dataset. You might want to first check all components you modified are reasonable. If so, you could play around with different values for background class weight and the gamma (see Implementation in our paper).
