### ISSUE TITLE
could you share the scripts spliting coco datasets into base and novel class datasets? and the  contents of 'concepts.txt' file? Thanks advance!

### ISSUE THREAD

**Issue by SamXiaosheng** [microsoft/RegionCLIP#78]

**Comment by YiwuZhong** [comment]
The dataset was provided by OVR paper (Open-vocabulary object detection using captions). You could look into their script for splitting COCO dataset. concepts.txt is simply a file with each row as a class name. See the instruction about creating concept embedding for more details.
