### ISSUE TITLE
How much GPU memory do we need to run RegionCLIP

### ISSUE THREAD

**Issue by Xuefei98** [microsoft/RegionCLIP#79]
First of all, great work and thank you for open source all the code! I wonder how much gpu memory do we need to run RegionCLIP?
Thanks,

Xuefei

**Comment by YiwuZhong** [comment]
It depends on how large the batch size is. Since our model adopts the architecture of Faster RCNN, it requires a similar GPU memory as Faster RCNN. You can refer to the model zoo in Detectron2 for more details.
