### ISSUE TITLE
I found that no 'TEXT_EMB_PATH' and no 'OPENSET_TEST_TEXT_EMB_PATH' are not effective for transferring learning 

### ISSUE THREAD

**Issue by SamXiaosheng** [microsoft/RegionCLIP#80]
Hi, I am readlly interseted in your work, I found that no 'TEXT_EMB_PATH' and no 'OPENSET_TEST_TEXT_EMB_PATH' are not effective for transferring learning. so  dose it not use text embeding?

**Comment by YiwuZhong** [comment]
Hi @SamXiaosheng, thanks for your interest. We did use text emb during transfer learning. I don't quite understand your question here. Could you elaborate on it?

**Comment by SamXiaosheng** [comment]
![image](https://github.com/microsoft/RegionCLIP/assets/20429609/e12b82f0-7f2e-4998-af80-c6d6f77b8241)
for example, i explanatory note tha last two raws.

**Comment by YiwuZhong** [comment]
@SamXiaosheng If you comment out the last two rows, it will be a closed-set training, such as a regular faster rcnn. Your model can only predict the base categories seen in training.
