### ISSUE TITLE
how to train Fully Supervised Object Detection using my own dataset? What is the specific process of training？

### ISSUE THREAD

**Issue by ReusJeffery** [microsoft/RegionCLIP#84]
Hello, great job! Could you please tell me how to train Fully Supervised Object Detection using my own dataset? What is the specific process of training?

**Comment by YiwuZhong** [comment]
@ReusJeffery Fully-supervised training is simply the default training of Detectron2, which uses labels of all categories. Please refer to Detectron2 for training on your own dataset. The only major difference is to initialize the model with our pre-trained RegionCLIP.
