### ISSUE TITLE
 CUDA out of memory

### ISSUE THREAD

**Issue by SunshineBread** [microsoft/RegionCLIP#88]
Hi, I’m not very familiar with the code structure of this project. When I run the scripts in the readme, I encounter a ‘cuda out of memory’ error. Could you please advise me on how to modify the code so that the program can run?

**Comment by YiwuZhong** [comment]
@SunshineBread You can try reducing the batch size. For example, [the parameter in any config file](https://github.com/microsoft/RegionCLIP/blob/4b8513b56e24827e3d6468e1f2105869f35c2d0b/configs/COCO-InstanceSegmentation/CLIP_fast_rcnn_R_50_C4_ovd.yaml#L49).
